=== OSGeo/grass/gui/wxpython/xml/main_menu.dtd
<!ELEMENT toolbox (label, items)>
<!ATTLIST toolbox name NMTOKEN #REQUIRED>

<!ELEMENT items ((subtoolbox | user-toolboxes-list)*)>

<!ELEMENT subtoolbox EMPTY>
<!ATTLIST subtoolbox name NMTOKEN #REQUIRED>

<!ELEMENT user-toolboxes-list EMPTY>

<!ELEMENT label (#PCDATA)>

=== OSGeo/grass/gui/wxpython/xml/main_menu.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE toolbox SYSTEM "main_menu.dtd">
<toolbox name="DefaultMainMenu">
  <label>Default GRASS GIS main menu bar</label>
  <items>
    <subtoolbox name="File"/>
    <subtoolbox name="Settings"/>
    <subtoolbox name="Raster"/>
    <subtoolbox name="Vector"/>
    <subtoolbox name="Imagery"/>
    <subtoolbox name="Volumes"/>
    <subtoolbox name="Database"/>
    <subtoolbox name="Temporal"/>
    <subtoolbox name="Help"/>
  </items>
</toolbox>

=== OSGeo/grass/gui/wxpython/xml/module_tree.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE toolbox SYSTEM "main_menu.dtd">
<toolbox name="DefaultModuleTree">
  <label>Default GRASS module tree</label>
  <items>
    <subtoolbox name="ImportExportLink"/>
    <subtoolbox name="ManageMaps"/>
    <subtoolbox name="Region"/>
    <subtoolbox name="Raster"/>
    <subtoolbox name="Vector"/>
    <subtoolbox name="Imagery"/>
    <subtoolbox name="Volumes"/>
    <subtoolbox name="Database"/>
    <subtoolbox name="Temporal"/>
    <subtoolbox name="GuiTools"/>
    <subtoolbox name="Other"/>
    <user-toolboxes-list/>
    <addons/>
  </items>
</toolbox>
