=== OSGeo/grass/gui/wxpython/xml/toolboxes.dtd
<!ELEMENT toolboxes (toolbox*)>

<!ELEMENT toolbox (label, items)>
<!ATTLIST toolbox name NMTOKEN #REQUIRED>

<!ELEMENT items ((module-item | wxgui-item | subtoolbox | separator)*)>

<!-- Subelement label is mandatory, however this may change in the future. -->
<!ELEMENT module-item (label, module?, description?, keywords?)>
<!ATTLIST module-item name NMTOKEN #REQUIRED>

<!ELEMENT wxgui-item (label?, ((handler, related-module?) | command)?, description?, keywords?, shortcut?, wx-id?)>
<!ATTLIST wxgui-item name NMTOKEN #REQUIRED>

<!--
Element subtoolbox could use xlink syntax but it is not much supported,
so it would be useless. Used syntax is easier and more conforms to other
elements which are not typical candidates for xlink use.
-->
<!ELEMENT subtoolbox EMPTY>
<!ATTLIST subtoolbox name NMTOKEN #REQUIRED>

<!ELEMENT separator EMPTY>

<!ELEMENT label (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT handler (#PCDATA)>
<!ELEMENT command (#PCDATA)>
<!ELEMENT module (#PCDATA)>
<!ELEMENT related-module (#PCDATA)>
<!ELEMENT keywords (#PCDATA)>
<!ELEMENT shortcut (#PCDATA)>
<!ELEMENT wx-id (#PCDATA)>

=== OSGeo/grass/gui/wxpython/xml/toolboxes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE toolboxes SYSTEM "toolboxes.dtd">
<toolboxes>
  <toolbox name="File">
    <label>&amp;File</label>
    <items>
      <subtoolbox name="Workspace"/>
      <subtoolbox name="MapDisplay"/>
      <separator/>
      <subtoolbox name="ImportRasterData"/>
      <subtoolbox name="ImportVectorData"/>
      <subtoolbox name="Import3DRasterData"/>
      <subtoolbox name="ImportDatabaseTable"/>
      <separator/>
      <subtoolbox name="ExportRasterMap"/>
      <subtoolbox name="ExportVectorMap"/>
      <subtoolbox name="Export3DRasterMaps"/>
      <subtoolbox name="ExportDatabaseTable"/>
      <separator/>
      <subtoolbox name="LinkExternalData"/>
      <separator/>
      <subtoolbox name="ManageMaps"/>
      <subtoolbox name="MapTypeConversions"/>
      <separator/>
      <wxgui-item name="Georectify"/>
      <separator/>
      <wxgui-item name="GraphicalModeler"/>
      <wxgui-item name="RunModel"/>
      <separator/>
      <wxgui-item name="AnimationTool"/>
      <separator/>
      <wxgui-item name="CartographicComposer"/>
      <wxgui-item name="MapSwipe"/>
      <separator/>
      <wxgui-item name="LaunchScript"/>
      <wxgui-item name="PyEdit"/>
      <separator/>
      <wxgui-item name="CloseGUI"/>
      <wxgui-item name="Quit"/>
    </items>
  </toolbox>
  <toolbox name="Settings">
    <label>&amp;Settings</label>
    <items>
      <subtoolbox name="Region"/>
      <subtoolbox name="GRASSWorkingEnvironment"/>
      <subtoolbox name="MapProjections"/>
      <separator/>
      <subtoolbox name="AddonsExtensions"/>
      <separator/>
      <wxgui-item name="Preferences"/>
    </items>
  </toolbox>
  <toolbox name="Raster">
    <label>&amp;Raster</label>
    <items>
      <subtoolbox name="DevelopRasterMap"/>
      <subtoolbox name="ManageRasterColors"/>
      <subtoolbox name="QueryRasterMaps"/>
      <subtoolbox name="RasterMapTypeConversions"/>
      <separator/>
      <subtoolbox name="RasterBufferDistance"/>
      <module-item name="r.mask">
        <label>Mask</label>
      </module-item>
      <module-item name="r.mask.status">
        <label>Query mask status</label>
      </module-item>
      <subtoolbox name="RasterMapCalculator"/>
      <subtoolbox name="NeighborhoodAnalysis"/>
      <subtoolbox name="OverlayRasters"/>
      <subtoolbox name="SolarRadianceAndShadows"/>
      <subtoolbox name="TerrainAnalysis"/>
      <subtoolbox name="TransformFeatures"/>
      <separator/>
      <subtoolbox name="HydrologicModeling"/>
      <subtoolbox name="GroundwaterModeling"/>
      <subtoolbox name="LandscapePatchAnalysis"/>
      <subtoolbox name="WildfireModeling"/>
      <separator/>
      <subtoolbox name="ChangeCategoryValuesAndLabels"/>
      <separator/>
      <subtoolbox name="GenerateRandomCells"/>
      <subtoolbox name="GenerateSurfaces"/>
      <subtoolbox name="InterpolateSurfaces"/>
      <separator/>
      <subtoolbox name="RasterReportsAndStatistics"/>
    </items>
  </toolbox>
  <toolbox name="Vector">
    <label>&amp;Vector</label>
    <items>
      <subtoolbox name="DevelopVectorMap"/>
      <subtoolbox name="TopologyMaintenance"/>
      <subtoolbox name="ManageVectorColors"/>
      <subtoolbox name="QueryVectorMap"/>
      <subtoolbox name="FeatureSelection"/>
      <subtoolbox name="VectorMapTypeConversions"/>
      <separator/>
      <module-item name="v.buffer">
        <label>Buffer vectors</label>
      </module-item>
      <subtoolbox name="PointAnalysis"/>
      <subtoolbox name="LidarAnalysis"/>
      <subtoolbox name="LinearReferencing"/>
      <module-item name="v.distance">
        <label>Nearest features</label>
      </module-item>
      <subtoolbox name="NetworkAnalysis"/>
      <subtoolbox name="OverlayVectorMaps"/>
      <separator/>
      <subtoolbox name="ManageCategories"/>
      <subtoolbox name="UpdateAttributes"/>
      <separator/>
      <module-item name="v.in.region">
        <label>Generate area for current region</label>
      </module-item>
      <subtoolbox name="GenerateAreasFromPoints"/>
      <module-item name="v.mkgrid">
        <label>Generate grid</label>
      </module-item>
      <subtoolbox name="GeneratePoints"/>
      <separator/>
      <subtoolbox name="VectorReportsAndStatistics"/>
    </items>
  </toolbox>
  <toolbox name="Imagery">
    <label>&amp;Imagery</label>
    <items>
      <subtoolbox name="DevelopImagesAndGroups"/>
      <subtoolbox name="ManageImageColors"/>
      <separator/>
      <module-item name="i.rectify">
        <label>Rectify image or raster</label>
      </module-item>
      <wxgui-item name="Histogram"/>
      <module-item name="i.spectral">
        <label>Spectral response</label>
      </module-item>
      <separator/>
      <module-item name="i.pansharpen">
        <label>Pan sharpening</label>
      </module-item>
      <subtoolbox name="ClassifyImage"/>
      <subtoolbox name="FilterImage"/>
      <subtoolbox name="TransformImage"/>
      <separator/>
      <subtoolbox name="SatelliteImagesTools"/>
      <subtoolbox name="ImageryGuiTools"/>
      <subtoolbox name="SatelliteImagesProducts"/>
      <subtoolbox name="EvapotranspirationCalculation"/>
      <separator/>
      <subtoolbox name="ImageryReportsAndStatistics"/>
    </items>
  </toolbox>
  <toolbox name="ImageryGuiTools">
    <label>Orthophoto tools</label>
    <items>
      <wxgui-item name="ManagingGCPsfor3DCorrection">
        <label>Manage GCPs for 3D correction</label>
      </wxgui-item>
      <wxgui-item name="CorrectsScanningDistortions">
        <label>Corrects scanning distortions</label>
      </wxgui-item>
      <separator/>
      <module-item name="i.ortho.init">
        <label>Initialize ortho parameters</label>
      </module-item>
      <module-item name="i.ortho.camera">
        <label>Camera parameters</label>
      </module-item>
      <module-item name="i.ortho.elev">
        <label>Elevation model for orthorectification</label>
      </module-item>
      <module-item name="i.ortho.target">
        <label>Target group for orthorectification</label>
      </module-item>
      <module-item name="i.ortho.transform">
        <label>Compute ortho transformation</label>
      </module-item>
      <module-item name="i.ortho.rectify">
        <label>Orthorectify imagery</label>
      </module-item>
    </items>
  </toolbox>
  <toolbox name="Volumes">
    <label>3D r&amp;aster</label>
    <items>
      <subtoolbox name="DevelopVolumes"/>
      <subtoolbox name="Raster3dMapTypeConversions"/>
      <separator/>
      <module-item name="r3.colors">
        <label>3D color tables</label>
      </module-item>
      <module-item name="r3.colors.out">
        <label>Export 3D color table</label>
      </module-item>
      <separator/>
      <module-item name="r3.mask">
        <label>3D mask</label>
      </module-item>
      <wxgui-item name="VolumeCalculator"/>
      <module-item name="r3.cross.rast">
        <label>Cross section</label>
      </module-item>
      <module-item name="r3.gwflow">
        <label>Groundwater modeling</label>
      </module-item>
      <module-item name="r3.flow">
        <label>3D flow lines</label>
      </module-item>
      <module-item name="r3.gradient">
        <label>3D gradient</label>
      </module-item>
      <module-item name="r3.neighbors">
        <label>3D neighborhood analysis</label>
      </module-item>
      <module-item name="r3.mkdspf">
        <label>Create 3D display file</label>
      </module-item>
      <module-item name="v.vol.rst">
        <label>Interpolate 3D raster from points</label>
      </module-item>
      <separator/>
      <subtoolbox name="Raster3dReportsAndStatistics"/>
    </items>
  </toolbox>
  <toolbox name="Database">
    <label>&amp;Database</label>
    <items>
      <subtoolbox name="DatabaseInformation"/>
      <separator/>
      <subtoolbox name="ManageDatabases"/>
      <subtoolbox name="Query"/>
      <separator/>
      <subtoolbox name="VectorDatabaseConnections"/>
    </items>
  </toolbox>
  <toolbox name="Help">
    <label>&amp;Help</label>
    <items>
      <wxgui-item name="GRASSHelp"/>
      <wxgui-item name="GUIHelp"/>
      <separator/>
      <wxgui-item name="AboutSystem"/>
      <wxgui-item name="AboutGRASSGIS"/>
    </items>
  </toolbox>
  <toolbox name="Workspace">
    <label>Workspace</label>
    <items>
      <wxgui-item name="New"/>
      <wxgui-item name="Open"/>
      <wxgui-item name="Save"/>
      <wxgui-item name="SaveAs"/>
      <wxgui-item name="Close"/>
    </items>
  </toolbox>
  <toolbox name="MapDisplay">
    <label>Map display</label>
    <items>
      <wxgui-item name="AddRaster"/>
      <wxgui-item name="AddVector"/>
      <wxgui-item name="AddMultipleRastersOrVectors"/>
      <wxgui-item name="AddRGB"/>
      <wxgui-item name="AddWebServiceLayer"/>
      <separator/>
      <wxgui-item name="NewMapDisplayWindow"/>
      <wxgui-item name="RenderAllMapDisplays"/>
      <wxgui-item name="CloseCurrentMapDisplayWindow"/>
      <wxgui-item name="CloseAllOpenMapDisplayWindows"/>
    </items>
  </toolbox>
  <toolbox name="ImportExportLink">
    <label>Import, export and link data</label>
    <items>
      <subtoolbox name="ImportRasterData"/>
      <subtoolbox name="ImportVectorData"/>
      <subtoolbox name="Import3DRasterData"/>
      <subtoolbox name="ImportDatabaseTable"/>
      <separator/>
      <subtoolbox name="ExportRasterMap"/>
      <subtoolbox name="ExportVectorMap"/>
      <subtoolbox name="Export3DRasterMaps"/>
      <subtoolbox name="ExportDatabaseTable"/>
      <separator/>
      <subtoolbox name="LinkExternalData"/>
    </items>
  </toolbox>
  <toolbox name="ImportRasterData">
    <label>Import raster data</label>
    <items>
      <wxgui-item name="CommonRasterFormats"/>
      <module-item name="r.in.gdal">
        <label>Import of common raster formats</label>
      </module-item>
      <separator/>
      <module-item name="r.in.xyz">
        <label>ASCII x,y,z point import and gridding</label>
