=== OSGeo/grass/gui/wxpython/xml/wxgui_items.dtd
<!ELEMENT wxgui-items (wxgui-item*)>

<!ELEMENT wxgui-item (label, ((handler, related-module?) | command), description, keywords?, shortcut?, wx-id?)>
<!ATTLIST wxgui-item name NMTOKEN #REQUIRED>

<!ELEMENT label (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT handler (#PCDATA)>
<!ELEMENT command (#PCDATA)>
<!ELEMENT related-module (#PCDATA)>
<!ELEMENT keywords (#PCDATA)>
<!ELEMENT shortcut (#PCDATA)>
<!ELEMENT wx-id (#PCDATA)>

=== OSGeo/grass/gui/wxpython/xml/wxgui_items.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE wxgui_items SYSTEM "wxgui_items.dtd">
<wxgui-items>
  <wxgui-item name="Georectify">
    <label>Georectify</label>
    <handler>OnGCPManager</handler>
    <related-module>g.gui.gcp</related-module>
    <description>Manage Ground Control Points for Georectification</description>
    <icon>georectify</icon>
  </wxgui-item>
  <wxgui-item name="GraphicalModeler">
    <label>Graphical modeler</label>
    <handler>OnGModeler</handler>
    <related-module>g.gui.gmodeler</related-module>
    <description>Launch Graphical modeler</description>
    <keywords>general,gui,graphical modeler,workflow</keywords>
    <icon>modeler-main</icon>
  </wxgui-item>
  <wxgui-item name="RunModel">
    <label>Run model</label>
    <handler>OnRunModel</handler>
    <description>Run model prepared by Graphical modeler</description>
  </wxgui-item>
  <wxgui-item name="AnimationTool">
    <label>Animation tool</label>
    <handler>OnAnimationTool</handler>
    <related-module>g.gui.animation</related-module>
    <description>Launch animation tool.</description>
    <keywords>general,gui,display</keywords>
  </wxgui-item>
  <wxgui-item name="TimelineTool">
    <label>Timeline tool</label>
    <handler>OnTimelineTool</handler>
    <related-module>g.gui.timeline</related-module>
    <description>Plot temporal extents.</description>
    <keywords>general,gui,temporal</keywords>
  </wxgui-item>
  <wxgui-item name="TplotTool">
    <label>Temporal plot tool</label>
    <handler>OnTplotTool</handler>
    <related-module>g.gui.tplot</related-module>
    <description>Plot temporal values.</description>
    <keywords>general,gui,temporal</keywords>
  </wxgui-item>
  <wxgui-item name="CartographicComposer">
    <label>Cartographic Composer</label>
    <handler>OnPsMap</handler>
    <related-module>g.gui.psmap</related-module>
    <description>Launch Cartographic Composer</description>
    <keywords>postscript,printing</keywords>
    <icon>print-compose</icon>
  </wxgui-item>
  <wxgui-item name="MapSwipe">
    <label>Map Swipe</label>
    <handler>OnMapSwipe</handler>
    <related-module>g.gui.mapswipe</related-module>
    <description>Launch Map Swipe</description>
    <keywords>general,gui,display</keywords>
  </wxgui-item>
  <wxgui-item name="LaunchScript">
    <label>Launch script</label>
    <handler>OnRunScript</handler>
    <description>Launches script file.</description>
  </wxgui-item>
  <wxgui-item name="PyEdit">
    <label>Simple Python Editor</label>
    <handler>OnSimpleEditor</handler>
    <description>Launches Simple Python Editor.</description>
  </wxgui-item>
  <wxgui-item name="RestartGUI">
    <label>Restart GUI</label>
    <handler>OnRestartWindow</handler>
    <description>Restart graphical user interface.</description>
  </wxgui-item>
  <wxgui-item name="CloseGUI">
    <label>Close GUI</label>
    <handler>OnCloseWindow</handler>
    <description>Close graphical user interface.</description>
  </wxgui-item>
  <wxgui-item name="Quit">
    <label>Quit GRASS GIS</label>
    <handler>OnCloseWindowOrExit</handler>
    <description>Close GUI and exit GRASS GIS shell.</description>
    <shortcut>Ctrl+Q</shortcut>
    <wx-id>ID_EXIT</wx-id>
  </wxgui-item>
  <wxgui-item name="Preferences">
    <label>Preferences</label>
    <handler>OnPreferences</handler>
    <description>User GUI preferences (display font, commands, digitizer, etc.)</description>
    <wx-id>ID_PREFERENCES</wx-id>
  </wxgui-item>
  <wxgui-item name="Histogram">
    <label>Histogram</label>
    <handler>OnHistogram</handler>
    <description>Generate histogram of image</description>
  </wxgui-item>
  <wxgui-item name="VolumeCalculator">
    <label>3D raster map calculator</label>
    <handler>OnMapCalculator</handler>
    <related-module>r3.mapcalc</related-module>
    <description>3D raster map calculator</description>
    <keywords>raster,algebra</keywords>
  </wxgui-item>
  <wxgui-item name="GRASSHelp">
    <label>GRASS help</label>
    <command>g.manual -i</command>
    <description>Display the HTML man pages of GRASS GIS</description>
    <keywords>general,manual,help</keywords>
    <wx-id>ID_HELP</wx-id>
  </wxgui-item>
  <wxgui-item name="GUIHelp">
    <label>GUI help</label>
    <command>g.manual entry=wxGUI</command>
    <description>Display the HTML man pages of GRASS GIS</description>
    <keywords>general,manual,help</keywords>
  </wxgui-item>
  <wxgui-item name="AboutSystem">
    <label>About system</label>
    <handler>OnSystemInfo</handler>
    <description>Prints system information</description>
  </wxgui-item>
  <wxgui-item name="AboutGRASSGIS">
    <label>About GRASS GIS</label>
    <handler>OnAboutGRASS</handler>
    <description>About GRASS GIS</description>
    <wx-id>ID_ABOUT</wx-id>
  </wxgui-item>
  <wxgui-item name="New">
    <label>New</label>
    <handler>OnWorkspaceNew</handler>
    <description>Create new workspace</description>
    <shortcut>Ctrl+N</shortcut>
    <wx-id>ID_NEW</wx-id>
  </wxgui-item>
  <wxgui-item name="Open">
    <label>Open</label>
    <handler>OnWorkspaceOpen</handler>
    <description>Load workspace from file</description>
    <shortcut>Ctrl+O</shortcut>
    <wx-id>ID_OPEN</wx-id>
  </wxgui-item>
  <wxgui-item name="Save">
    <label>Save</label>
    <handler>OnWorkspaceSave</handler>
    <description>Save workspace</description>
    <shortcut>Ctrl+S</shortcut>
    <wx-id>ID_SAVE</wx-id>
  </wxgui-item>
  <wxgui-item name="SaveAs">
    <label>Save as</label>
    <handler>OnWorkspaceSaveAs</handler>
    <description>Save workspace to file</description>
    <wx-id>ID_SAVEAS</wx-id>
  </wxgui-item>
  <wxgui-item name="Close">
    <label>Close</label>
    <handler>OnWorkspaceClose</handler>
    <description>Close workspace file</description>
    <wx-id>ID_CLOSE</wx-id>
  </wxgui-item>
  <wxgui-item name="AddRaster">
    <label>Add raster</label>
    <handler>OnAddRaster</handler>
    <description>Add raster map layer to current display</description>
    <shortcut>Ctrl+Shift+R</shortcut>
  </wxgui-item>
  <wxgui-item name="AddVector">
    <label>Add vector</label>
    <handler>OnAddVector</handler>
    <description>Add vector map layer to current display</description>
    <shortcut>Ctrl+Shift+V</shortcut>
  </wxgui-item>
  <wxgui-item name="AddMultipleRastersOrVectors">
    <label>Add multiple rasters or vectors</label>
    <handler>OnAddMaps</handler>
    <description>Add multiple raster or vector map layers to current display</description>
    <shortcut>Ctrl+Shift+L</shortcut>
  </wxgui-item>
  <wxgui-item name="AddRGB">
    <label>Add RGB raster layer</label>
    <handler>OnAddRasterRGB</handler>
    <description>Add RGB raster map layer to current display</description>
  </wxgui-item>
  <wxgui-item name="AddWebServiceLayer">
    <label>Add web service layer</label>
    <handler>OnAddWS</handler>
    <description>Add web service layer</description>
  </wxgui-item>
  <wxgui-item name="NewMapDisplayWindow">
    <label>New map display window</label>
    <handler>OnNewDisplay</handler>
    <description>Open new map display window</description>
  </wxgui-item>
  <wxgui-item name="RenderAllMapDisplays">
    <label>Render all map displays</label>
    <handler>OnRenderAllMapDisplays</handler>
    <description>Re-render maps in all open map display windows</description>
    <shortcut>Ctrl+R</shortcut>
  </wxgui-item>
  <wxgui-item name="CloseCurrentMapDisplayWindow">
    <label>Close current map display window</label>
    <handler>OnDisplayClose</handler>
    <description>Close current map display window</description>
    <shortcut>Ctrl+W</shortcut>
  </wxgui-item>
  <wxgui-item name="CloseAllOpenMapDisplayWindows">
    <label>Close all open map display windows</label>
    <handler>OnDisplayCloseAll</handler>
    <description>Close all open map display windows</description>
  </wxgui-item>
  <wxgui-item name="CommonRasterFormats">
    <label>Simplified raster import with reprojection</label>
    <handler>OnImportGdalLayers</handler>
    <related-module>r.import</related-module>
    <description>Imports raster data into a GRASS raster map using GDAL library.</description>
    <keywords>raster,import</keywords>
  </wxgui-item>
  <wxgui-item name="CommonVectorFormats">
    <label>Simplified vector import with reprojection</label>
    <handler>OnImportOgrLayers</handler>
    <related-module>v.import</related-module>
    <description>Imports vector data into a GRASS vector map using OGR library.</description>
    <keywords>vector,import</keywords>
  </wxgui-item>
  <wxgui-item name="DXFImport">
    <label>DXF import</label>
    <handler>OnImportDxfFile</handler>
    <related-module>v.in.dxf</related-module>
    <description>Converts files in DXF format to GRASS vector map format.</description>
    <keywords>vector,import,dxf</keywords>
  </wxgui-item>
  <wxgui-item name="LinkExternalRasterData">
    <label>Link external raster data</label>
    <handler>OnLinkGdalLayers</handler>
    <related-module>r.external</related-module>
    <description>Link GDAL supported raster data as a pseudo GRASS raster map layer.</description>
    <keywords>raster,import,input,external</keywords>
  </wxgui-item>
  <wxgui-item name="LinkExternalVectorData">
    <label>Link external vector data</label>
    <handler>OnLinkOgrLayers</handler>
    <related-module>v.external</related-module>
    <description>Creates a new pseudo-vector map as a link to an OGR-supported layer.</description>
    <keywords>vector,import,input,external,OGR,PostGIS</keywords>
  </wxgui-item>
  <wxgui-item name="OutputFormatForVectorData">
    <label>Output format for vector data</label>
    <handler>OnVectorOutputFormat</handler>
    <related-module>v.external.out</related-module>
    <description>Defines vector output format utilizing OGR library.</description>
    <keywords>vector,export,output,external,OGR,PostGIS</keywords>
  </wxgui-item>
  <wxgui-item name="ShowRegion">
    <label>Show current region</label>
